// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khtegkbzwxrwbqpijodg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtodGVna2J6d3hyd2JxcGlqb2RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNzAzODYsImV4cCI6MjA1NDY0NjM4Nn0.YK_xPZ6hwSp5EQI0gSFeHNs9HkTe0BOe4ihPnp44jWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);